import React from 'react';
import type {CaseReport,Advisory} from '../lib/types';
import {Icon,categoryIcon,State,ImageView,Button,date,Badge,Empty} from './ui';
export function ReportsTable({items,onOpen}:{items:CaseReport[];onOpen:(id:string)=>void}){
 if(!items.length)return <Empty title="No reports match this view"/>;
 return <div className="table-wrap"><table className="table"><thead><tr><th>Report / observation</th><th>Community</th><th>Status</th><th>Submitted</th><th><span className="sr-only">Action</span></th></tr></thead><tbody>{items.map(r=><tr key={r.id}><td><div className="row"><span className={'iconbox '+r.category}><Icon name={categoryIcon(r.category)}/></span><div><strong>{r.title}</strong><small>{r.code} • {r.species||r.category}</small></div></div></td><td>{r.area_name}</td><td><State state={r.state}/></td><td><small>{date(r.created_at)}</small></td><td><Button variant="ghost small" onClick={()=>onOpen(r.id)}>Open <Icon name="arrow" size={15}/></Button></td></tr>)}</tbody></table></div>;
}
export function ReportList({items,onOpen}:{items:CaseReport[];onOpen:(id:string)=>void}){return <div className="report-list">{items.map(r=><button className="report-row" key={r.id} onClick={()=>onOpen(r.id)}><span className={'iconbox '+r.category}><Icon name={categoryIcon(r.category)}/></span><div className="grow"><strong>{r.title}</strong><small>{r.code} • {r.area_name}</small><State state={r.state}/></div><Icon name="arrow" size={17}/></button>)}{!items.length&&<Empty title="Your reports will appear here"/>}</div>;}
export function AdvisoryCard({item,onOpen}:{item:Advisory;onOpen:()=>void}){return <article className="card advisory"><div className="row between"><span className={'iconbox '+item.category}><Icon name={categoryIcon(item.category)}/></span><div className="row"><State state={item.state}/>{!item.read&&item.state==='published'&&<Badge tone="blue">New</Badge>}</div></div><h3>{item.title}</h3><p>{item.body}</p><small>{item.area_name} • {date(item.published_at)}</small><Button variant="ghost" onClick={onOpen}>Read advisory <Icon name="arrow" size={16}/></Button></article>;}
